# Assignment 10
## Due July 03th
### names: Jennifer Them, Florence Lopez

In [72]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from numpy import linalg as LA
from sklearn.metrics.pairwise import euclidean_distances
from numpy.linalg import inv, eig
from random import randint


np.random.seed(42)

In [73]:
import scipy.io
mat = scipy.io.loadmat('assignment10data.mat')
X = mat['X']
X.mean(0)

array([0.01316662, 0.07437076])

## Exercise 1

### a)

In [80]:
def KMeans(X, k):
    n = len(X)
    random_centers = []
    assigned_clusters = np.ones(n)
    old_clusters = []
    
    # chose random centers 
    for i in range(k):
        random_centers.append(X[randint(0, n-1)])
    
    while not np.array_equal(old_clusters, assigned_clusters):
    #for epochs in range(100):
    # assign clusters 
        for j in range(len(X)):
            dists = euclidean_distances(random_centers, X[j].reshape(1, -1))
            cluster = np.argmin(dists)
            assigned_clusters[j] = cluster

        old_clusters = assigned_clusters 

        # compute new cluster centers
        for i in range(k):
            if np.where(assigned_clusters == i)[0].size != 0: 
                assigned = X[np.where(assigned_clusters == i)[0]] # points that were assigned to this cluster
                random_centers[i] = assigned.mean(0)

    return random_centers, assigned_clusters, old_clusters
    #return random_centers 

In [81]:
# test KMeans
centers, clusters, old = KMeans(X, 5)
clusters

array([4., 4., 0., 4., 0., 4., 2., 4., 2., 4., 0., 4., 4., 4., 4., 4., 0.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 0., 4.,
       4., 4., 4., 4., 4., 0., 4., 4., 4., 4., 4., 0., 4., 4., 4., 0., 4.,
       4., 4., 4., 4., 4., 0., 4., 4., 0., 4., 4., 4., 0., 0., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 2., 4., 4., 4., 4., 0., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 0., 4.,
       4., 4., 2., 0., 0., 4., 4., 4., 1., 1., 2., 1., 1., 1., 2., 2., 1.,
       1., 1., 1., 1., 2., 1., 2., 2., 1., 2., 2., 1., 1., 2., 2., 2., 2.,
       2., 2., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       2., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 2., 2.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2.,
       1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2., 1., 1., 2., 2., 2., 2.,
       1., 2., 1., 1., 1., 2., 1., 2., 2., 1., 2., 1., 1., 2., 1., 1., 0.,
       3., 2., 1., 1., 1.

In [82]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=5)
kmeans.fit(X)
y_kmeans = kmeans.predict(X)
y_kmeans

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       1, 4, 0, 3, 3, 0, 3, 3, 0, 0, 4, 2, 0, 2, 4, 1, 3, 2, 0, 2, 0, 2,
       2, 1, 3, 3, 0, 2, 3, 1, 0, 1, 0, 0, 4, 1, 3, 3, 0, 3, 1, 2, 1, 2,
       0, 2, 0, 4, 3, 1, 4, 2, 1, 3, 1, 1, 4, 2, 1, 0, 4, 1, 4, 1, 1, 1,
       0, 2, 1, 0, 0, 2, 4, 4, 1, 0, 2, 2, 4, 1, 2,

### b)

### c)

In [9]:
def spectralClustering(W, k, normalised):
    pass